apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-entry-chart
  labels:
    mesitis/kind: "catalog-entry"
    mesitis/enabled: "true"
data:
  wrapped-resource: |
    {
        "team": "api",
        "offering": "time-service",
        "description":"A time service available through a helm chart registry, offered by the API team",
        "uuid":"4",
        "version":"1",
        "whitelist": ["client-ns"],
        "provisionhelmchart": {
            "charturl": "http://nginx-chart-registry.default.svc.cluster.local/charts/trivial-time-service-0.1.0.tgz",
			"namespace":"provider-ns",
			"name":"trivial-time-service"
        },
        "credentialfromcatalog": {
            "username":"iamtheuser",
            "password":"iamthepassword"
        }
    }
