apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-entry-api-service
  labels:
    mesitis/kind: "catalog-entry"
    mesitis/enabled: "true"
data:
  wrapped-resource: |
    {
        "team": "api",
        "offering": "api-service",
        "description":"An api service offered by the API team",
        "uuid":"3",
        "version":"1",
        "whitelist": ["client-ns"],
        "provisionnewclusterobjects": {
            "namespace": "provider-ns",
            "name": "api-service",
            "labelSelector":"mesitis/offering=api-service"
        },
        "credentialfromcatalog": {
            "username":"iamtheuser",
            "password":"iamthepassword"
        }
    }
