apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: time-service-instance
spec:
  clusterServiceClassExternalName: api-time-service
  clusterServicePlanExternalName: api-time-service-1
