apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mesitis-role-binding
subjects:
- apiGroup: 
  kind: ServiceAccount
  name: mesitis-user
  namespace: provider-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: ClusterRole
  name: mesitis-role
