apiVersion: v1
kind: ConfigMap
metadata:
  name: wrapped-api-service
  labels:
    mesitis/offering: "api-service"
    mesitis/kind: "wrapped-service"
    mesitis/enabled: "true"
    mesitis/order: "2"
data:
  wrapped-resource: |
    {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
        "name": "back-end-service",
        "labels": {
          "app": "back-end"
        }
      },
      "spec": {
        "selector":{
            "app":"back-end"
        },
        "ports": [
            {
            "protocol": "TCP",
            "port": 80,
            "targetPort": 9000
            }]
        }
    }
